# Generated by Django 4.2.4 on 2023-08-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=50)),
                ('task_priority', models.CharField(max_length=10)),
                ('task_due_date', models.DateField()),
                ('task_status', models.BooleanField(default=False)),
            ],
        ),
    ]
