# Generated by Django 4.2.4 on 2023-08-30 06:15

from django.db import migrations, models
import todos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='task_priority',
            field=models.CharField(max_length=4, validators=[todos.validators.PriorityValidator()]),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='task_title',
            field=models.CharField(max_length=45),
        ),
    ]
