# Generated by Django 4.2.4 on 2023-09-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todotask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='task_priority',
            field=models.IntegerField(),
        ),
    ]
